# Generated by Django 4.2.2 on 2023-06-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=400)),
                ('basic_salary', models.FloatField()),
                ('working_days', models.FloatField()),
                ('overtime', models.FloatField()),
                ('bonus', models.FloatField()),
                ('house_allow', models.FloatField()),
                ('predtime', models.FloatField()),
                ('transport_allowance', models.FloatField()),
                ('telephone_allowance', models.FloatField()),
                ('gross_salary', models.FloatField()),
                ('taxable_income', models.FloatField()),
                ('tax_by_percent', models.FloatField()),
                ('tax_by_number', models.FloatField()),
                ('pensions', models.FloatField()),
                ('cost_sharing', models.FloatField()),
                ('social', models.FloatField()),
                ('loan', models.FloatField()),
                ('penality', models.FloatField()),
                ('total_deduction', models.FloatField()),
                ('net_pay', models.FloatField()),
                ('bank_account', models.FloatField()),
            ],
        ),
    ]
