# Generated by Django 4.2.2 on 2023-06-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollmodel',
            old_name='transport_allowance_predime',
            new_name='transport_allowance_prediem',
        ),
    ]
