# Generated by Django 4.2.2 on 2023-06-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LetterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_type', models.CharField(max_length=100)),
                ('letter_head', models.CharField(max_length=100000)),
                ('to_whom_it_concern', models.CharField(max_length=100000)),
                ('employee_name', models.CharField(max_length=100000)),
                ('content', models.CharField(max_length=100000)),
                ('letter_writer', models.CharField(max_length=100000)),
                ('letter_writer_title', models.CharField(max_length=100000)),
                ('company_name', models.CharField(max_length=100000)),
            ],
        ),
    ]
